openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Device Management - Configuration
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/configurations/{componentId}:
    get:
      tags:
        - Device Management - Configuration
      summary: Read a single Configuration
      operationId: deviceConfigurationRead
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../deviceConfiguration/deviceConfiguration.yaml#/components/parameters/componentId'
        - $ref: './deviceConfiguration.yaml#/components/parameters/configurationFormat'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      responses:
        200:
          description: The Configuration details of a single Service on a single Device
          content:
            application/json:
              schema:
                $ref: './deviceConfiguration.yaml#/components/schemas/componentConfigurations'
            application/xml:
              schema:
                $ref: './deviceConfiguration.yaml#/components/schemas/componentConfigurationsInputXml'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
